const hasPackage = require('../../utils/has_package')

class EslintGenerator extends require('yeoman-generator') {
  constructor(opts, args) {
    super(opts, args)
    this._state = {
      isPrettier: false,
    }
  }

  async initializing() {
    this._state.isPrettier = hasPackage.call(this, 'prettier')
  }

  async configuring() {
    let deps = ['eslint']
    if (this._state.isPrettier) {
      deps.push('eslint-config-prettier', 'eslint-plugin-prettier')
    }
    await this.addDevDependencies(deps)
  }

  writing() {
    this.fs.copyTpl(
      this.templatePath('eslintignore.ejs'),
      this.destinationPath('.eslintignore'),
    )
  }

  async end() {
    await this.spawnCommand('npx', ['eslint', '--init'])

    // writing here to overwrite eslintrc.js generated by 'npx eslint --init'
    this.fs.copyTpl(
      this.templatePath('eslintrc.js.ejs'),
      this.destinationPath('.eslintrc.js'),
      {
        isPrettier: this._state.isPrettier,
      },
    )
  }
}

module.exports = EslintGenerator
